name: Trigger Azure Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trugger Azure Devops Pipeline
        uses: Azure/pipelines@v1.2
        with:
          azure-devops-project-url: ${{ secrets.AZURE_DEVOPS_PROJECT_URL }}
          azure-pipeline-name: "zkeser.devopsTest"
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
          
